##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maalmarkus/public_html/veebiarendus/portfoolio/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R backup $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R emailer $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp CV.pdf $DEPLOYPATH
    - /bin/cp CV_en.pdf $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp education.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp practice.html $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH
